DROP TABLE IF EXISTS `sys_template`;
CREATE TABLE `sys_template` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `sorting` int(11) NOT NULL DEFAULT 0,
  `description` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL DEFAULT '',
  `root` smallint(5) unsigned NOT NULL DEFAULT 0,
  `clear` smallint(5) unsigned NOT NULL DEFAULT 0,
  `include_static_file` text DEFAULT NULL,
  `constants` text DEFAULT NULL,
  `config` text DEFAULT NULL,
  `basedOn` tinytext DEFAULT NULL,
  `includeStaticAfterBasedOn` smallint(5) unsigned NOT NULL DEFAULT 0,
  `static_file_mode` smallint(5) unsigned NOT NULL DEFAULT 0,
  `tx_impexp_origuid` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `roottemplate` (`deleted`,`hidden`,`root`),
  KEY `parent` (`pid`,`deleted`,`hidden`)
);

CREATE TABLE tt_content (
    `tx_impexp_origuid` int(11) NOT NULL DEFAULT 0,
  `tx_mask_accordian` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_grid` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_heading` mediumtext DEFAULT NULL,
  `tx_mask_image` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_image_hover_content` mediumtext DEFAULT NULL,
  `tx_mask_loop` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_option` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_pdfheading` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_profile_content` mediumtext DEFAULT NULL,
  `tx_mask_profile_header` mediumtext DEFAULT NULL,
  `tx_mask_slider` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_title` mediumtext DEFAULT NULL,
  `tx_mask_banner_backimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_banner` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_donatebtn` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_donatelink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_treeicon` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_headblack` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_headspan` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_text` mediumtext DEFAULT NULL,
  `tx_mask_readlink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_readbtn` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_treeimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_giftitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_img` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_rptimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testtitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_testttree` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testrpt` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_testitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_centerimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_subtitle` mediumtext DEFAULT NULL,
  `tx_mask_holitext` mediumtext DEFAULT NULL,
  `tx_mask_btntxt` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_holidaylink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_holidayimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_holidaytitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_tree` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_formtitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_footerdate` date DEFAULT NULL,
  `tx_mask_footertxt` mediumtext DEFAULT NULL,
  `tx_mask_content_parent_uid` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_tablenames` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_maplink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_socialmedia` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_copytxt` mediumtext DEFAULT NULL,
  `tx_mask_copylink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_linktxt` mediumtext DEFAULT NULL,
  `tx_mask_form` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_role` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_menu` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_menus` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_sitmap` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_abouttext` mediumtext DEFAULT NULL,
  `tx_mask_contact_form` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_header_info` mediumtext DEFAULT NULL,
  `tx_mask_holiday_info` mediumtext DEFAULT NULL,
  `tx_mask_map` mediumtext DEFAULT NULL,
  `tx_mask_about_icon` int(10) unsigned NOT NULL DEFAULT 0,
  KEY `tx_mask_content_parent_uid` (`tx_mask_content_parent_uid`)
);

DROP TABLE IF EXISTS `tx_mask_banner`;
CREATE TABLE `tx_mask_banner` (
 `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_subtitle` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_date` date DEFAULT NULL,
  `tx_mask_button` mediumtext DEFAULT NULL,
  `tx_mask_btnlink` varchar(255) NOT NULL DEFAULT '',
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  `tx_mask_slider_desc` mediumtext DEFAULT NULL,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_rptimg`;
CREATE TABLE `tx_mask_rptimg` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_sliderimg` int(10) unsigned NOT NULL DEFAULT 0,
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_testrpt`;
CREATE TABLE `tx_mask_testrpt` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_picture` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_info` mediumtext DEFAULT NULL,
  `tx_mask_name` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_information` mediumtext DEFAULT NULL,
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`deleted`,`hidden`),
  KEY `translation_source` (`l10n_source`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);